# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  schedule:
  - cron:  "0 10 * * Sun"
  workflow_dispatch:
  
jobs:
  build:
    timeout-minutes: 5
    runs-on: ubuntu-latest

    steps:
      
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: '14'
        cache: 'npm'
    - run: npm ci
    - run: npx playwright install-deps
    - run: npm run debug
      env:
        EMAIL: ${{ secrets.EMAIL }} 
        PASSWORD: ${{ secrets.PASSWORD }}
